version: "3"

services:
  ijulia:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./tutorial:/home/jovyan/tutorial
      - ./examples:/home/jovyan/examples
#      - /path/on/your/drive:/home/jovyan/work # use if you want "work" to persist
#      - ./src:/LatticeQM/src # use if you want modify LatticeQM "on-the-fly"
#      - ./Project.toml:/LatticeQM/Project.toml # use if you want modify LatticeQM "on-the-fly"
    environment:
      julia_version: 1.6.2
      JUPYTER_ENABLE_LAB: "yes"