name = "LatticeQM"
uuid = "606d2a7e-9b17-11e9-1c5c-455b84f60309"
authors = ["Tobias Wolf <wolft@itp.phys.ethz.ch>"]
version = "0.5.1"

[deps]
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ParallelUtilities = "fad6cfc8-4f83-11e9-06cc-151124046ad0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
