name = "LatticeQM"
uuid = "606d2a7e-9b17-11e9-1c5c-455b84f60309"
authors = ["Tobias Wolf <wolft@itp.phys.ethz.ch>"]
version = "0.5.1"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Homebrew = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
InspectDR = "d0351b0e-4b05-5898-87b3-e2a8edfddd1d"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
