name = "LatticeQM"
uuid = "606d2a7e-9b17-11e9-1c5c-455b84f60309"
authors = ["Tobias Wolf <wolft@itp.phys.ethz.ch>"]
version = "0.5.6"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
